`timescale 1ns/1ns

/*  timer_minsec_tb.v
*   Test a minutes and two-digit seconds timer block.
*   with a master clock / 7 
*   tick rate.
*/

`define CLK_DIV 7


//Part 1:  Implement a testbench that simulates and verifies the timer_minsec design.  
//         Your module design must use the assignment API definition:
module timer_minsec_tb (
    output wire [3:0] sec_low_digit,
    output wire [2:0] sec_high_digit,
    output wire [3:0] min_low_digit
);

    //Simulation signals and module interconnects
    reg clk;
    reg pause = 1'b1;
    reg up_down = 1'b1;
    wire sec_low_dig_load;
    wire sec_low_dig_enable;
    wire sec_high_dig_load;
    wire min_low_dig_load;

    //Generate the clock waveform
    initial begin
	clk = 0;
	forever
	begin
	    #5 clk = ~clk;
	end
    end

    //Instantiate clock_divider instance classed CD_UUT to generate 
    //the enable signal for the seconds low digit (sec_low_dig_enable).
    //Set CLK_DIV_INT to the defined constant CLK_DIV
    //Set clk, pause to this module's internal signals.
    clock_divider #(.CLK_DIV_INT(`CLK_DIV)) CD_UUT (.clk(clk), .pause(pause), .rco_enable(sec_low_dig_enable));

    //Instantiate a timer_minsec instanced called UUT.
    //Set clk and up_down to this module's internal signals.
    //Set enable to sec_low_dig_enable generated by the clock divider.
    //Generate sec_low_digit, sec_high_digit, and min_low_digit.
    timer_minsec UUT (.clk(clk), .enable(sec_low_dig_enable), .up_down(up_down), .sec_low_digit(sec_low_digit), 
	.sec_high_digit(sec_high_digit), .min_low_digit(min_low_digit));

    //Access internal signals to assign to simulation outputs
    assign sec_low_dig_load = UUT.sec_low_load;
    assign sec_high_dig_load = UUT.sec_high_load;
    assign min_low_dig_load = UUT.min_low_load;

    //Simulate 
    initial begin
       #100     //Enable count
          pause = 1'b0;  
       #43000   //Count backwards
          up_down = 1'b0;
       #37000   //Disable count
          pause = 1'b1;
    end
endmodule